import canonicalLaneMathlib.AdmissibleClass
import ComputerGraphicsVisualizationCanonicalLaneLean.RenderingEquation
import ComputerGraphicsVisualizationCanonicalLaneLean.RasterizationPipeline
import ComputerGraphicsVisualizationCanonicalLaneLean.RayTracingIntegrator
import ComputerGraphicsVisualizationCanonicalLaneLean.TextureMapping
import ComputerGraphicsVisualizationCanonicalLaneLean.VisibilityDetermination

namespace HautevilleHouse
namespace ComputerGraphicsVisualizationCanonicalLaneLean

def ConstrainedGraphicsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_graphics_endgame (A : AdmissibleClass) :
    ConstrainedGraphicsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end ComputerGraphicsVisualizationCanonicalLaneLean
end HautevilleHouse